runtime: python39
instance_class: F2
entrypoint: gunicorn -b :$PORT main:app

handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: auto

env_variables:
  ENVIRONMENT: "production"
  SECRET_KEY: "igorek_sk"
