runtime: python39

instance_class: F2

entrypoint: gunicorn -b :$PORT main:app

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto

env_variables:
  ENVIRONMENT: production
  GOOGLE_CLIENT_ID: "your-client-id"
  GOOGLE_CLIENT_SECRET: "your-client-secret"
  SECRET_KEY: "your-secret-key"
